#!/bin/sh
set -e

UPSTREAM_VERSION=""
UPSTREAM_URL=""

while [ $# -gt 0 ]; do
	case $1 in
	--upstream-version)
		UPSTREAM_VERSION=$2
		shift 2
		;;
	*)
		break;
		;;
	esac
done

UPSTREAM_URL=`sed '2!d;s/ .*//;s#/[^/]*$#/#' debian/watch`

trap "rm -f tarsnap-sigs-${UPSTREAM_VERSION}.asc" EXIT
BASE=`pwd`

cd ..
wget -q ${UPSTREAM_URL}/tarsnap-sigs-${UPSTREAM_VERSION}.asc

/usr/bin/gpgv --homedir /dev/null --keyring ${BASE}/debian/upstream/signing-key.asc tarsnap-sigs-${UPSTREAM_VERSION}.asc

sha256sum --status -c tarsnap-sigs-${UPSTREAM_VERSION}.asc


